[tool.poetry]
name = "aiges_python"
version = "0.1.0"
description = "A module for test aiges's python wrapper.py"
authors = ["maybaby <ybyang7@iflytek.com>"]
license = "Apache License Version 2.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
